### PR TITLE
Feature ftp support

### PR DESCRIPTION
**Pull request by IngaAl**
This change is [Reviewable](https://reviewable.io/reviews/qualisystemslab/cloudshell-orch-sandbox/13)

### CODE REVIEW

**Comment by ayeleta** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 523 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVeRHNBhR5l-NUWNlH:-KZVeRHNBhR5l-NUWNlI:bp9ugkb) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L523)):*
> ```Python
>             self.sandbox.report_error("Failed to create dir " + dir_name +
>                                       " on  the FTP server. Error is: " + str(e), write_to_output_window=False, raise_error=True)
> ```

Please rename the call from self.create_src_file_on_tftp to self.create_src_file_on_storage
and move the call to be before catching the exception

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 620 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVdCQZbhgRFZOOkKz-:-KZVdCQZbhgRFZOOkKz0:bxrx96s) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L620)):*
> ```Python
>     # ----------------------------------
>     # ----------------------------------
> ```

Please delete the temp file after getting the data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13)*

**Comment by AlonSaggie** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13)*

**Comment by AlonSaggie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 523 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVeRHNBhR5l-NUWNlH:-KZZPNd9V014OA88gSeK:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L523)):*
<details><summary><i>Previously, ayeleta wrote…</i></summary><blockquote>

Please rename the call from self.create_src_file_on_tftp to self.create_src_file_on_storage
and move the call to be before catching the exception
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 620 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVdCQZbhgRFZOOkKz-:-KZZPI6nmDBWyfFuD4Lc:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L620)):*
<details><summary><i>Previously, ayeleta wrote…</i></summary><blockquote>

Please delete the temp file after getting the data
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13)*

**Comment by AlonSaggie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-:-KZZPpdTuu-hgNdE1lXx:bnfp4nl)*

**Comment by AlonSaggie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 523 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVeRHNBhR5l-NUWNlH:-KZZQGTg2A7yPiDT8Kx8:bb6ywmx) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L523)):*
<details><summary><i>Previously, AlonSaggie (Alon Saggie) wrote…</i></summary><blockquote>

OK
</blockquote></details>

LGTM

---

*[sandbox_scripts/QualiEnvironmentUtils/StorageManager.py, line 620 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13#-KZVdCQZbhgRFZOOkKz-:-KZZQ2Vj82lD3MZtl8cJ:bb6ywmx) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/81c1ed90f7612f8aa6771b2b3d9d54ce0ac51058/sandbox_scripts/QualiEnvironmentUtils/StorageManager.py#L620)):*
<details><summary><i>Previously, AlonSaggie (Alon Saggie) wrote…</i></summary><blockquote>

OK
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/13)*

**Pull request merged**
