### PR TITLE
Add regression tests

### PR DESCRIPTION
**Pull request by ayeleta**
Regression tests + unit tests of the Sandbox class

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystemslab/cloudshell-orch-sandbox/14)

### CODE REVIEW

**Comment by kalsky** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 207 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKreL_Ask1eomybIRV:-KcKreL_Ask1eomybIRW:bnezrkd) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L207)):*
> ```Python
> 
>         self.sandbox.clear_all_resources_live_status()
>         self.mock_api_session.return_value.SetResourceLiveStatus.assert_called()
> ```

check that the api was called twice

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 225 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKrHP6CGZhIqj2z77_:-KcKrHP7CxpmHPu9HYtf:bdb6mu4) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L225)):*
> ```Python
> 
>         self.sandbox.clear_all_resources_live_status()
>         self.mock_api_session.return_value.SetResourceLiveStatus.assert_called()
> ```

1. add assert not called for services
2. check that set live status api called twice

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 292 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKsozfCuWE9TCWZEaf:-KcKsozfCuWE9TCWZEag:bpbk24c) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L292)):*
> ```Python
>         self.mock_api_session.return_value.GetReservationDetails = Mock(return_value=rdi)
>         self.sandbox.activate_connectors(True)
>         self.mock_api_session.return_value.ConnectRoutesInReservation.assert_called()
> ```

check that this api was called with the second connector (connectionfailed)

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 349 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKtQCV6g9vjwx8QemC:-KcKtQCV6g9vjwx8QemD:b78st5q) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L349)):*
> ```Python
> 
>     #================================================================
>     #test activate_routes
> ```

update the comment

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 386 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKv3y_pjcXD9VC8ZUS:-KcKv3y_pjcXD9VC8ZUT:b-h6y7fw) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L386)):*
> ```Python
>         self.sandbox.get_root_resources = Mock(return_value=rr)
>         self.sandbox.power_on_vms()
>         self.mock_api_session.return_value.ExecuteResourceConnectedCommand.assert_called_with('5487c6ce-d0b3-43e9-8ee7-e27af8406905', 'r2', 'PowerOn', 'power')
> ```

should be r1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by kalsky** [comment]
Reviewed 16 of 19 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by kalsky** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by kalsky** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 207 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKreL_Ask1eomybIRV:-KcMGuYw8RMEYbxIDC8B:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L207)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

check that the api was called twice
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 225 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKrHP6CGZhIqj2z77_:-KcMGwaT2fkNRUpRqWMI:br1b9os) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L225)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

1. add assert not called for services
2. check that set live status api called twice
</blockquote></details>

function actually removed. OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 292 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKsozfCuWE9TCWZEaf:-KcMH034PlNGf71kbhgf:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L292)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

check that this api was called with the second connector (connectionfailed)
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 349 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKtQCV6g9vjwx8QemC:-KcMH1_w7RRTKLHYhoyS:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L349)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

update the comment
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 386 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKv3y_pjcXD9VC8ZUS:-KcMH2Nukog-eX3t_zkM:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L386)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

should be r1
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by kalsky** [comment]
OK

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-:-KcMH8Y0tqugmp_DMkpj:b32w0x)*

**Comment by kalsky** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 225 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKrHP6CGZhIqj2z77_:-KcMI_1_zSjJzJAnn6xR:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L225)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

function actually removed. OK
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by kalsky** [comment]
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-:-KcMIkgqGA5q1pmrEMia:bb6ywmx)*

**Comment by ayeleta** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 207 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKreL_Ask1eomybIRV:-KcOfwyFXrvPzMewcyrf:b2nhksp) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L207)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Comment by ayeleta** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 225 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKrHP6CGZhIqj2z77_:-KcOgDWSLGEOV-F39RhS:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L225)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 292 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKsozfCuWE9TCWZEaf:-KcOgKocEIiMCZQzrTL9:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L292)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 349 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKtQCV6g9vjwx8QemC:-KcOgOAJUGTx5KTaENKk:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L349)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

---

*[sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py, line 386 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14#-KcKv3y_pjcXD9VC8ZUS:-KcOgPHhCTq_YKFBE7zm:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/291f0e73495eb4d4e5bc144972746a3ddc43d531/sandbox_scripts/QualiEnvironmentUtils/tests/test_Sandbox.py#L386)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/14)*

**Pull request merged**
