### PR TITLE
Refactor savenrestore gitlab

### PR DESCRIPTION
**Pull request by jimbr70**
changes to gitlab client, some messaging, various fixzes from merge.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystemslab/cloudshell-orch-sandbox/21)

### CODE REVIEW

**Comment by kalsky** [comment]
Review status: 0 of 10 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sandbox_scripts/environment/setup/setup_resources.py, line 10 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki715SmHfUCKqVHhlIw:-Ki715SmHfUCKqVHhlIx:b-5v9mgj) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L10)):*
> ```Python
> import os, sys
> ```

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.
this is also affecting the tests we're running.

also in the os.environ line you just override the value you got from cloudshell in a real execution so it needs to be removed from this file anyway.

---

*[sandbox_scripts/environment/setup/setup_resources.py, line 77 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki71XjvyTUFWKRRomGk:-Ki71XjvyTUFWKRRomGl:bydji38) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L77)):*
> ```Python
>             self.logger.error("Setup failed. Unexpected error:" + str(sys.exc_info()[0]))
> ```

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.

---

*[sandbox_scripts/environment/teardown/teardown_resources.py, line 26 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki71kkatghVAWp_Oxg0:-Ki71kkatghVAWp_Oxg1:b974f8u) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/teardown/teardown_resources.py#L26)):*
> ```Python
>             if saveNRestoreTool.get_storage_manager():
>                 ignore_models = ['Generic TFTP server', 'Config Set Pool', 'Generic FTP server', 'netscout switch 3912',
>                              'OnPATH Switch 3903', 'Ixia Traffic generator', "SubNet-28", "SubNet-30"]
> ```

are you missing the gitlab model here?

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 131 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73TMCQmpq1JEhiRRG:-Ki73TMDiET1hJnMrH3d:b-37dfq9) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L131)):*
> ```Python
>                 if command.Name == 'restore':
>                     for parm in command.Parameters:
>                         print "****" + parm.Name + "****"
> ```

this print might appear in the output, we should remove it

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 132 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73X4Rt2TrOnGcO0NU:-Ki73X4Rt2TrOnGcO0NV:brezznq) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L132)):*
> ```Python
>                     for parm in command.Parameters:
>                         print "****" + parm.Name + "****"
>                         if parm.Name in "path, src_Path, xx123":
> ```

no need for the xx123 i guess (same as yy123, zzz123 below)
also, you're just checking if the param name is inside this string, not inside a list of values like this:
a = ["aaa","bbb","ccc"]
if "bbb" in a:

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 140 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74dG1sjM9kUXYCJi3:-Ki74dG2XwYceZ1Slt0b:b-hzhx8v) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L140)):*
> ```Python
> 
>             if the_path == "undef" or the_cfgtype == "undef" or the_restoremeth == "undef":
>                 raise "Failed to find viable restore command for " + self.name \
> ```

why not raising a QualiError?

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 144 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74gBqlQSJrUhT55dp:-Ki74gBqlQSJrUhT55dq:b-hzhx8v) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L144)):*
> ```Python
> 
>         except:
>             raise "Failed building restore command input parm names."
> ```

why not raising a QualiError?

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 150 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74kjIWNpiVJ91NrNm:-Ki74kjIWNpiVJ91NrNn:be7bqfu) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L150)):*
> ```Python
>                               InputNameValue(the_cfgtype, str(config_type)),
>                               InputNameValue(the_restoremeth, str(restore_method))]
>             print "resource.py L124 " + self.name + "  configuration_type = " + str(config_type)
> ```

remove any (debug) prints, they might appear in the output

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 162 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki75AFevKwqa75rByYQ:-Ki75AFevKwqa75rByYR:b-r7anoh) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L162)):*
> ```Python
> 
>         except QualiError as qerror:
>             print "ERROR1: Load config file failed. " + qerror.message
> ```

remove (debug) prints

---

*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 167 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki75DpeV4CxZ6yGlfcb:-Ki75DpeV4CxZ6yGlfcc:b-r7anoh) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L167)):*
> ```Python
> 
>         except:
>             print "ERROR2: Load config file failed. "
> ```

remove (debug) prints

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/environment/setup/setup_resources.py, line 10 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki715SmHfUCKqVHhlIw:-KiBNNaUDNP6N5fg17UK:bn0gti8) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L10)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.
this is also affecting the tests we're running.

also in the os.environ line you just override the value you got from cloudshell in a real execution so it needs to be removed from this file anyway.
</blockquote></details>

change made

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
*[sandbox_scripts/environment/setup/setup_resources.py, line 10 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki715SmHfUCKqVHhlIw:-KiBMzS7ApOHWV674I9Y:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L10)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.
this is also affecting the tests we're running.

also in the os.environ line you just override the value you got from cloudshell in a real execution so it needs to be removed from this file anyway.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
*[sandbox_scripts/environment/setup/setup_resources.py, line 77 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki71XjvyTUFWKRRomGk:-KiBNveHjIKuAJIV-dWq:b32w0x) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L77)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/environment/teardown/teardown_resources.py, line 26 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki71kkatghVAWp_Oxg0:-KiBO030kieoMONnJoZ5:bcti5zg) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/teardown/teardown_resources.py#L26)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

are you missing the gitlab model here?
</blockquote></details>

Done. change made

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 131 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73TMCQmpq1JEhiRRG:-KiBO3wxvjb0goh59vS_:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L131)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

this print might appear in the output, we should remove it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 132 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73X4Rt2TrOnGcO0NU:-KiBOErHQHEsL44z6cl-:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L132)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

no need for the xx123 i guess (same as yy123, zzz123 below)
also, you're just checking if the param name is inside this string, not inside a list of values like this:
a = ["aaa","bbb","ccc"]
if "bbb" in a:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 140 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74dG1sjM9kUXYCJi3:-KiBOGMfiKvUjVluU9vr:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L140)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

why not raising a QualiError?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 144 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74gBqlQSJrUhT55dp:-KiBOMZDoKQuti3bRtbN:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L144)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

why not raising a QualiError?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 150 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74kjIWNpiVJ91NrNm:-KiBONrywu978ybTGVnL:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L150)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

remove any (debug) prints, they might appear in the output
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 132 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73X4Rt2TrOnGcO0NU:-KiBOLiCtO0QM-als0ND:b-z8psy6) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L132)):*
<details><summary><i>Previously, jimbr70 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can't see it that it's done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 162 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki75AFevKwqa75rByYQ:-KiBOQaja4tXIIvEABuR:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L162)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

remove (debug) prints
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 167 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki75DpeV4CxZ6yGlfcb:-KiBOTgUE80lo8-45459:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L167)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

remove (debug) prints
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sandbox_scripts/environment/setup/setup_resources.py, line 10 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki715SmHfUCKqVHhlIw:-KiBNmzwKv-C4jyYtJdC:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L10)):*
<details><summary><i>Previously, jimbr70 wrote…</i></summary><blockquote>

change made
</blockquote></details>

Done.

---

*[sandbox_scripts/environment/setup/setup_resources.py, line 77 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki71XjvyTUFWKRRomGk:-KiBNrqLOeTuP5UDUi8M:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/environment/setup/setup_resources.py#L77)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

please remove these lines from the setup_resources file, you can add them in a test file that later will call/use this class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 140 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74dG1sjM9kUXYCJi3:-KiBOz-x0uGE25qYvjda:b-j7dd95) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L140)):*
<details><summary><i>Previously, jimbr70 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can't see that it's done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 132 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki73X4Rt2TrOnGcO0NU:-KiBYjQskqdhRVcgf1mk:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L132)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

can't see it that it's done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by jimbr70** [comment]
*[sandbox_scripts/QualiEnvironmentUtils/Resource.py, line 140 at r1](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21#-Ki74dG1sjM9kUXYCJi3:-KiBYoD9GQ8hjeCUwZYJ:b-896fix) ([raw file](https://github.com/qualisystemslab/cloudshell-orch-sandbox/blob/75e42c897e0e1a0405a085e53d9454afaaf5197a/sandbox_scripts/QualiEnvironmentUtils/Resource.py#L140)):*
<details><summary><i>Previously, kalsky wrote…</i></summary><blockquote>

can't see that it's done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
Reviewed 4 of 10 files at r1, 6 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Comment by kalsky** [comment]
Reviewed 1 of 3 files at r4, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/cloudshell-orch-sandbox/21)*

**Pull request merged**
